services:
  backend:
      image: backend:dev
      build: ../backend
      ports:
        - "8001:8000"
      environment:
        MODEL_NAME: weather-model
        DEV_ENV: True
  frontend:
      image: frontend:dev
      build: ../frontend
      environment:
        FLASK_BACKEND_NAME: backend-dev
      ports:
       - "8080:80"
  