services:
  backend:
      image: backend:production
      build: ../backend
      ports:
        - "8001:8000"
      environment:
        MODEL_NAME: weather-model
        MODEL_ALIAS: Production
        MLFLOW_TRACKING_URI: ${DAGSHUB_MLFLOW_TRACKING_URI}
        MLFLOW_TRACKING_TOKEN: ${DAGSHUB_TOKEN}
  frontend:
      image: frontend:production
      build: ../frontend
      environment:
        FLASK_BACKEND_NAME: backend
      ports:
       - "8080:80"
  